name: "ğŸŒ· publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: ğŸŒ· publish
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘‰ checkout
        uses: actions/checkout@v3
      - name: ğŸ node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: ğŸŒ· publish
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
